baseurl = "/"
languageCode = "uk"
theme = "terminal"
paginate = 10
defaultContentLanguage = "uk"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "Зміст" # default

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.uk]
    languageName = "Українська"
    title = "jUst QA blog"
    subtitle = "Протестувати все неможливо. Але є те, що необхідно чи достатньо"
    owner = "В'ячеслав Клевченя"
    keywords = "QA, testing, test automation, motivation"
    copyright = ""
    menuMore = "Більше"
    readMore = "Читати далі"
    readOtherPosts = "Інші записи"
    missingContentMessage = "Щось пішло не так і сторінка на знайшлась..."
    missingBackButtonLabel = "До головної"
    TocTitle = "Зміст"

    [languages.uk.params.logo]
      logoText = "jUst QA blog"
      logoHomeLink = "/"

    [languages.uk.menu]
      [[languages.uk.menu.main]]
        identifier = "cv"
        name = "Lead SDET/QA Automation Engineer"
        url = "/pages/cv"
      [[languages.uk.menu.main]]
        identifier = "documentation"
        name = "Публічні Нотатки"
        url = "https://docs.slavaqa.pp.ua"
